LanguageName = 'js'
LanguageDisplayName = "JS/TS"
InstallInstructions = '''

FOOOOOOO

Using npm or yarn, install the package. Typescript types are shipped with it.

```sh
npm install --save @vexilla/client
```

or

```sh
yarn add @vexilla/client
```
'''
CustomInstanceHash = "customInstanceHash"
SyncFlags = "fetchFlags"
SetupSnippet = '''
```javascript
this.client = new VexillaClient({
  baseUrl: 'https://BUCKET_NAME.s3-website-AWS_REGION.amazonaws.com',
  environment: process.env.ENVIRONMENT,
  customInstanceHash: userId
});
this.client.getFlags('features.json');
```
'''
Should = "should"
UsageSnippet = '''
```javascript
client.should(FEATURE_NAME)
```
'''
Example = '''
```javascript
import { VexillaClient } from '@vexilla/client';

export class FeatureFlagsService {
  private client;

  constructor() {
    this.client = new VexillaClient({
      baseUrl: 'https://BUCKET_NAME.s3-website-AWS_REGION.amazonaws.com',
      environment: process.env.ENVIRONMENT,
      customInstanceHash: userId
    });
    this.client.getFlags('features.json');
  }

  should(featureName) {
    return this.client?.should(featureName);
  }
}
```
'''
TestingInstructions='''

Inside of the docker container we need to allow the container to hit the test-server. This is only in local dev. The Github Action should be able to see it just fine. Maybe.

TEST_SERVER_HOST=host.docker.internal:3000 pytest
'''