typescript = """
if (client.should("GROUP_NAME_OR_ID", "FLAG_NAME_OR_ID")) {
  // do something
}
"""

rust = """
match client.should("GROUP_NAME_OR_ID", "FLAG_NAME_OR_ID") {
  Ok() => println!("Do the thing for the flag"),
  _ => println!("DON'T do the thing for the flag"),
};
"""
